// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPAFAE_j4wzJJXs7WN2N1AeOe9pxdHxa0',
    appId: '1:134826951635:web:2073ef0072925c18666526',
    messagingSenderId: '134826951635',
    projectId: 'search-party-gpthv',
    authDomain: 'search-party-gpthv.firebaseapp.com',
    storageBucket: 'search-party-gpthv.appspot.com',
    measurementId: 'G-MZL4517M9S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpdtuPxyGzKfuIzlbDBxE-0bZwiq3gSsU',
    appId: '1:134826951635:android:9d4e7820d3713509666526',
    messagingSenderId: '134826951635',
    projectId: 'search-party-gpthv',
    storageBucket: 'search-party-gpthv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKDIhm6lBVJ7CLWXTmKW9VFfbJoJjWJdY',
    appId: '1:134826951635:ios:8dfe36ec457d7b0d666526',
    messagingSenderId: '134826951635',
    projectId: 'search-party-gpthv',
    storageBucket: 'search-party-gpthv.appspot.com',
    iosBundleId: 'com.example.searchparty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKDIhm6lBVJ7CLWXTmKW9VFfbJoJjWJdY',
    appId: '1:134826951635:ios:8dfe36ec457d7b0d666526',
    messagingSenderId: '134826951635',
    projectId: 'search-party-gpthv',
    storageBucket: 'search-party-gpthv.appspot.com',
    iosBundleId: 'com.example.searchparty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPAFAE_j4wzJJXs7WN2N1AeOe9pxdHxa0',
    appId: '1:134826951635:web:77c92c1394477e92666526',
    messagingSenderId: '134826951635',
    projectId: 'search-party-gpthv',
    authDomain: 'search-party-gpthv.firebaseapp.com',
    storageBucket: 'search-party-gpthv.appspot.com',
    measurementId: 'G-5GYF55F168',
  );
}
